CREATE database circle_glucose;
USE circle_glucose;

SET SQL_SAFE_UPDATES = 1;

CREATE TABLE USUARIOS(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(45) NOT NULL,
    EMAIL VARCHAR(225) NOT NULL,
    SENHA VARCHAR(200) NOT NULL
);


CREATE TABLE GLICEMIAS_AO_LEVANT_USERS(  -- GLICEMIAS AO LEVANTAR
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT UNSIGNED NOT NULL,
	GLICEMIA INT UNSIGNED NOT NULL,
	DATA_GLICEMIA DATE NOT NULL,
	HORA_GLICEMIA TIME NOT NULL,
	CONSTRAINT FK_GLICEMIA_01_USER FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);

INSERT INTO glicemias_ao_levant_users(id_usuario, glicemia, data_glicemia, hora_glicemia) VALUES(3, 145, '21-11-09', '14:35');
SELECT * FROM glicemias_ao_levant_users WHERE id_usuario = 3;
SELECT * FROM glicemias_ao_levant_users;
DELETE FROM glicemias_ao_levant_users;

CREATE TABLE GLICEMIAS_ANT_ALMOC_USERS(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ID_USUARIO INT UNSIGNED NOT NULL,
	GLICEMIA INT UNSIGNED NOT NULL,
	DATA_GLICEMIA DATE NOT NULL,
	HORA_GLICEMIA TIME NOT NULL,
   	CONSTRAINT FK_GLICEMIA_02_USER FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);

CREATE TABLE GLICEMIAS_DEP_ALMOC_USERS(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    	ID_USUARIO INT UNSIGNED NOT NULL,
	GLICEMIA INT UNSIGNED NOT NULL,
    	DATA_GLICEMIA DATE NOT NULL,
    	HORA_GLICEMIA TIME NOT NULL,
    	CONSTRAINT FK_GLICEMIA_03_USER FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);

CREATE TABLE GLICEMIAS_ANT_LANC_USERS(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    	ID_USUARIO INT UNSIGNED NOT NULL,
	GLICEMIA INT UNSIGNED NOT NULL,
    	DATA_GLICEMIA DATE NOT NULL,
    	HORA_GLICEMIA TIME NOT NULL,
    	CONSTRAINT FK_GLICEMIA_04_USER FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);

CREATE TABLE GLICEMIAS_DEP_LANC_USERS(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    	ID_USUARIO INT UNSIGNED NOT NULL,
	GLICEMIA INT UNSIGNED NOT NULL,
    	DATA_GLICEMIA DATE NOT NULL,
    	HORA_GLICEMIA TIME NOT NULL,
    	CONSTRAINT FK_GLICEMIA_05_USER FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);

CREATE TABLE GLICEMIAS_ANT_JANT_USERS(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    	ID_USUARIO INT UNSIGNED NOT NULL,
	GLICEMIA INT UNSIGNED NOT NULL,
    	DATA_GLICEMIA DATE NOT NULL,
    	HORA_GLICEMIA TIME NOT NULL,
    	CONSTRAINT FK_GLICEMIA_06_USER FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);

CREATE TABLE GLICEMIAS_DEP_JANT_USERS(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    	ID_USUARIO INT UNSIGNED NOT NULL,
	GLICEMIA INT UNSIGNED NOT NULL,
    	DATA_GLICEMIA DATE NOT NULL,
    	HORA_GLICEMIA TIME NOT NULL,
    	CONSTRAINT FK_GLICEMIA_07_USER FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);

CREATE TABLE GLICEMIAS_AO_DORM_USERS(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    	ID_USUARIO INT UNSIGNED NOT NULL,
	GLICEMIA INT UNSIGNED NOT NULL,
    	DATA_GLICEMIA DATE NOT NULL,
    	HORA_GLICEMIA TIME NOT NULL,
    	CONSTRAINT FK_GLICEMIA_08_USER FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);

CREATE TABLE GLICEMIAS_NOT_PERIOD_USERS( -- COMO NÃO INFORMA O PERIODO, SERÁ ADICIONADA A HORA E DATA DO MOMENTO QUE FOI ADD
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    	ID_USUARIO INT UNSIGNED NOT NULL,
	GLICEMIA INT UNSIGNED NOT NULL,
    	DATA_GLICEMIA DATE NOT NULL,
    	HORA_GLICEMIA TIME NOT NULL,
    	CONSTRAINT FK_GLICEMIA_09_USER FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS (ID)
);




SELECT * FROM USUARIOS;
